inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Rails:
  Enabled: true

StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
